DROP TABLE IF EXISTS PassengerFlights;
DROP TABLE IF EXISTS Flights;
DROP TABLE IF EXISTS Passengers;
DROP TABLE IF EXISTS Airports;
DROP TABLE IF EXISTS Continents;
DROP TABLE IF EXISTS TempPassengers;